### ISSUE TITLE
How to make changes in author display page?

### ISSUE THREAD

**Issue by Shrey-Viradiya** [narative/gatsby-starter-novela#19]
I have added some extra entries in author object. Wanted to know how can I display them in the website?

```yaml
- name: "authors"
    label: "Authors"
    folder: "content/authors/authors"
    create: true
    delete: true
    format: "yml"
    identifier_field: "name"
    media_folder: "avatars"
    public_folder: "./avatars"
    editor:
      preview: false
    fields:
      - { label: Name, name: name, widget: string }
      - { label: Bio, name: bio, widget: string }
      - { label: Featured, name: featured, widget: boolean, default: false }
      - { label: Avatar, name: avatar, widget: image }
      - { label: Social, name: social, widget: list, collapsed: false, field: { label: URL, name: url, widget: string } }
      - label: Education
        name: education
        widget: list
        collapsed: false
        fields: 
          - {label: Institution, name: institution, widget: string}
          - {label: Stream, name: stream, widget: string}
          - {label: Year, name: year, widget: string, pattern: ['(19|20)\d{2}-(19|20)\d{2}$', "Should be in YYYY-YYYY format"] }
          - {label: Score, name: score, widget: number, value_type: float}
```
